const animalsList=[
    {
       id: 1,
       title: 'Beaver',
       imgAnimalWithTail: require('./img/animals_with_tail/beaver.png'),
       imgAnimalWithoutTail: require('./img/animals_without_tails/beaver_body.png'),
       imgAnimalTail: require('./img/tails/beaver_tail.png'),
       soundAnimalTitle: './sounds/animals_names/beaver.mp3',
       soundHowAnimalTell: './sounds/animals_sounds/beaver_tell.mp3',
    },
    {
       id: 2,
       title: 'Fox',
       imgAnimalWithTail: require('./img/animals_with_tail/fox.png'),
       imgAnimalWithoutTail: require('./img/animals_without_tails/fox_body.png'),
       imgAnimalTail: require('./img/tails/fox_teil.png'),
       soundAnimalTitle: './sounds/animals_names/fox.mp3',
       soundHowAnimalTell: './sounds/animals_sounds/fox_tell.mp3',
    },
     {
       id: 4,
       title: 'Dolphin',
       imgAnimalWithTail: require('./img/animals_with_tail/dolphin.png'),
       imgAnimalWithoutTail: require('./img/animals_without_tails/dolphin_body.png'),
       imgAnimalTail: require('./img/tails/dolphin_tail.png'),
       soundAnimalTitle: './sounds/animals_names/dolphin.mp3',
       soundHowAnimalTell: './sounds/animals_sounds/dolphin_tell.mp3',
    },
    {
       id: 5,
       title: 'Lion',
       imgAnimalWithTail: require('./img/animals_with_tail/lion.png'),
       imgAnimalWithoutTail: require('./img/animals_without_tails/lion_body.png'),
       imgAnimalTail: require('./img/tails/lion_tail.png'),
       soundAnimalTitle: './sounds/animals_names/lion.mp3',
       soundHowAnimalTell: './sounds/animals_sounds/lion_tell.mp3',
    },
    {
       id: 6,
       title: 'Monkey',
       imgAnimalWithTail: require('./img/animals_with_tail/monkey.png'),
       imgAnimalWithoutTail: require('./img/animals_without_tails/monkey_body.png'),
       imgAnimalTail: require('./img/tails/monkey_tail.png'),
       soundAnimalTitle: './sounds/animals_names/monkey.mp3',
       soundHowAnimalTell: './sounds/animals_sounds/monkey_tell.mp3',
    },
    {
       id: 7,
       title: 'Ostrich',
       imgAnimalWithTail: require('./img/animals_with_tail/ostrich.png'),
       imgAnimalWithoutTail: require('./img/animals_without_tails/ostrich_body.png'),
       imgAnimalTail: require('./img/tails/ostrich_tail.png'),
       soundAnimalTitle: './sounds/animals_names/ostrich.mp3',
       soundHowAnimalTell: './sounds/animals_sounds/ostrich_tell.mp3',
    },
    {
      id: 8,
      title: 'Cat',
      imgAnimalWithTail: require('./img/animals_with_tail/cat.png'),
      imgAnimalWithoutTail: require('./img/animals_without_tails/cat_body.png'),
      imgAnimalTail: require('./img/tails/cat_tail.png'),
      soundAnimalTitle: './sounds/animals_names/cat.mp3',
      soundHowAnimalTell: './sounds/animals_sounds/cat_tell.mp3',
   },
   {
      id: 9,
      title: 'Cock',
      imgAnimalWithTail: require('./img/animals_with_tail/cock.png'),
      imgAnimalWithoutTail: require('./img/animals_without_tails/cock_body.png'),
      imgAnimalTail: require('./img/tails/cock_tail.png'),
      soundAnimalTitle: './sounds/animals_names/cock.mp3',
      soundHowAnimalTell: './sounds/animals_sounds/cock_tell.mp3',
   },
   {
      id: 10,
      title: 'Giraffe',
      imgAnimalWithTail: require('./img/animals_with_tail/giraffe.png'),
      imgAnimalWithoutTail: require('./img/animals_without_tails/giraffe_body.png'),
      imgAnimalTail: require('./img/tails/giraffe_tail.png'),
      soundAnimalTitle: './sounds/animals_names/giraffe.mp3',
      soundHowAnimalTell: './sounds/animals_sounds/giraffe_tell.mp3',
    },
    {
      id: 11,
      title: 'Horse',
      imgAnimalWithTail: require('./img/animals_with_tail/horse.png'),
      imgAnimalWithoutTail: require('./img/animals_without_tails/horse_body.png'),
      imgAnimalTail: require('./img/tails/horse_tail.png'),
      soundAnimalTitle: './sounds/animals_names/horse.mp3',
      soundHowAnimalTell: './sounds/animals_sounds/horse_tell.mp3',
   },
   {
      id: 12,
      title: 'Mouse',
      imgAnimalWithTail: require('./img/animals_with_tail/mouse.png'),
      imgAnimalWithoutTail: require('./img/animals_without_tails/mouse_body.png'),
      imgAnimalTail: require('./img/tails/mouse_tail.png'),
      soundAnimalTitle: './sounds/animals_names/mouse.mp3',
      soundHowAnimalTell: './sounds/animals_sounds/mouse_tell.mp3',
   },
   {
      id: 13,
      title: 'Pig',
      imgAnimalWithTail: require('./img/animals_with_tail/pig.png'),
      imgAnimalWithoutTail: require('./img/animals_without_tails/pig_body.png'),
      imgAnimalTail: require('./img/tails/pig_tail.png'),
      soundAnimalTitle: './sounds/animals_names/pig.mp3',
      soundHowAnimalTell: './sounds/animals_sounds/pig_tell.mp3',
   },
   {
      id: 14,
      title: 'Rabbit',
      imgAnimalWithTail: require('./img/animals_with_tail/rabbit.png'),
      imgAnimalWithoutTail: require('./img/animals_without_tails/rabbit_body.png'),
      imgAnimalTail: require('./img/tails/rabbit_tail.png'),
      soundAnimalTitle: './sounds/animals_names/rabbit.mp3',
      soundHowAnimalTell: './sounds/animals_sounds/rabbit_tell.mp3',
   },
   {
      id: 15,
      title: 'Raccoon',
      imgAnimalWithTail: require('./img/animals_with_tail/raccoon.png'),
      imgAnimalWithoutTail: require('./img/animals_without_tails/raccoon_body.png'),
      imgAnimalTail: require('./img/tails/raccoon_tail.png'),
      soundAnimalTitle: './sounds/animals_names/raccoon.mp3',
      soundHowAnimalTell: './sounds/animals_sounds/raccoon_tell.mp3',
   },
   {
      id: 16,
      title: 'Skunk',
      imgAnimalWithTail: require('./img/animals_with_tail/skunk.png'),
      imgAnimalWithoutTail: require('./img/animals_without_tails/skunk_body.png'),
      imgAnimalTail: require('./img/tails/skunk_tail.png'),
      soundAnimalTitle: './sounds/animals_names/skunk.mp3',
      soundHowAnimalTell: './sounds/animals_sounds/skunk_tell.mp3',
   },
   {
      id: 17,
      title: 'Squirrel',
      imgAnimalWithTail: require('./img/animals_with_tail/squirrel.png'),
      imgAnimalWithoutTail: require('./img/animals_without_tails/squirrel_body.png'),
      imgAnimalTail: require('./img/tails/squirrel_tail.png'),
      soundAnimalTitle: './sounds/animals_names/squirrel.mp3',
      soundHowAnimalTell: './sounds/animals_sounds/squirrel_tell.mp3',
    },
    {
      id: 18,
      title: 'Tiger',
      imgAnimalWithTail: require('./img/animals_with_tail/tiger.png'),
      imgAnimalWithoutTail: require('./img/animals_without_tails/tiger_body.png'),
      imgAnimalTail: require('./img/tails/tiger_tail.png'),
      soundAnimalTitle: './sounds/animals_names/tiger.mp3',
      soundHowAnimalTell: './sounds/animals_sounds/tiger_tell.mp3',
   },
   {
      id: 19,
      title: 'Turkey',
      imgAnimalWithTail: require('./img/animals_with_tail/turkey.png'),
      imgAnimalWithoutTail: require('./img/animals_without_tails/turkey_body.png'),
      imgAnimalTail: require('./img/tails/turkey_tail.png'),
      soundAnimalTitle: './sounds/animals_names/turkey.mp3',
      soundHowAnimalTell: './sounds/animals_sounds/turkey_tell.mp3',
   }

          
]

   export default animalsList;
   
    